// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tree.Models;

namespace Trees.Solution.Migrations
{
    [DbContext(typeof(TreesContext))]
    [Migration("20211028175827_bud")]
    partial class bud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Tree.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Farm")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Strain")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 2,
                            Description = "This shit right here tho...PHEW buddy. Get ready!",
                            Farm = "GUD Gardens",
                            Strain = "In The Pines",
                            Type = "Sativa"
                        },
                        new
                        {
                            PlantId = 3,
                            Description = "Special Weapon will destroy you.",
                            Farm = "Deep Creek Gardens",
                            Strain = "Special Weapon",
                            Type = "Sativa"
                        },
                        new
                        {
                            PlantId = 4,
                            Description = "I know what a GRAPE is. What the fuck is a grape FRUIT?",
                            Farm = "Fox Hollow Flora",
                            Strain = "Grape Fluff",
                            Type = "Indica"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
